# This configmap stores the configuration used by cloudflared.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "changewatch-exporter.fullname" . }}
data:
  config.yaml: |
{{- toYaml .Values.config | nindent 4 }}